// Dữ liệu mẫu lớp 10A3 (45 học sinh thật)
window.SCHOOL_DATA = {
  metadata: {
    school: "Trường THPT Hai Bà Trưng",
    subject: "Sinh học",
    weights: { mouth: 1, small: 1, mid: 2, final: 3 }
  },
  students: [
    {id:1,name:'Nguyễn Thị Hoài An',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:2,name:'Đỗ Quốc Anh',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:3,name:'Kiều Tuấn Anh',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:4,name:'Lê Quốc Anh',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:5,name:'Đỗ Thị Ngọc Ánh',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:6,name:'Vũ Ngọc Ánh',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:7,name:'Phí Hoàng Bảo',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:8,name:'Lê Quý Châu',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:9,name:'Vương Thành Công',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:10,name:'Nguyễn Văn Dũng',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:11,name:'Kiều Xuân Dưỡng',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:12,name:'Nguyễn Minh Đức',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:13,name:'Cấn Thị Thu Hà',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:14,name:'Nguyễn Đăng Thành Hà',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:15,name:'Khuất Thị Thu Hạnh',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:16,name:'Phùng Thúy Hằng',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:17,name:'Phan Thanh Hiếu',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:18,name:'Đặng Thị Kim Hoa',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:19,name:'Phùng Việt Hoàng',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:20,name:'Vũ Ngọc Huy',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:21,name:'Nguyễn Thị Thanh Huyền',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:22,name:'Nguyễn Như Khang',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:23,name:'Khuất Gia Khánh',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:24,name:'Phùng Quốc Khánh',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:25,name:'Trần Vũ Duy Khánh',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:26,name:'Phan Nguyễn Bách Khâm',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:27,name:'Đặng Đình Khiêm',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:28,name:'Nguyễn Đăng Khoa',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:29,name:'Kiều Bảo Linh',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:30,name:'Vương Gia Linh',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:31,name:'Lại Ngọc Vân Long',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:32,name:'Lê Hồng Ngân',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:33,name:'Nguyễn Trung Nghĩa',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:34,name:'Đỗ Anh Ngọc',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:35,name:'Nguyễn Linh Nhi',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:36,name:'Nguyễn Đỗ Cao Phong',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:37,name:'Phùng Đức Phong',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:38,name:'Nguyễn Thế Quang',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:39,name:'Nguyễn Văn Quân',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:40,name:'Phí Văn Quyền',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:41,name:'Lưu Huyền Trang',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:42,name:'Nguyễn Thu Trang',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:43,name:'Nguyễn Ngọc Trâm',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:44,name:'Nguyễn Đức Tuấn Tú',class:'10A3',mouth:'',small:'',mid:'',final:''},
    {id:45,name:'Nguyễn Thị Tú',class:'10A3',mouth:'',small:'',mid:'',final:''}
  ]
};
